# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chroniken von Baradur | LARP f체r Hamburg
subtitle: Das beste LARP in Hamburg
email: larp-hamburg@webmail.de
description: >- # this means to ignore newlines until "baseurl:"
  LARPs & Cons in Hamburg f체r j체ngere und 채ltere Spieler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
instagram_username: larp_hamburg 
header: /assets/images/header.jpg
teaser: /assets/images/header.jpg
logo:   /assets/images/header.jpg # path of logo image to display in the masthead, e.g. "
# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Add pages
include: ["_pages"]

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-asciidoc
 
 

# Social Sharing
twitter:
  username               : "mmistakes"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : " assets/images/header.jpg"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://twitter.com/
    - https://github.com/
author:
  name             : "Christian Martens"
  avatar           : "/assets/images/leute/Christian.jpeg"
  bio              : "Christian Martens"
  location         : "Hamburg"
  links:
    - label: "Chroniken von Baradur"
      icon: "fas fa-fw fa-link"
      url: "http://www.larp-hamburg.de"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vogellacompany/larp-hamburg"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/larp_hamburg"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vogellacompany/larp-hamburg"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/larp_hamburg"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      classes: wide
  - scope:
      path: ""
      type: single
    values:
      layout: single
      read_time: false
      share: true
      related: false
      author_profile: true
      classes: wide
